sudo: false
language: java
jdk:
  - openjdk11
  - openjdk8
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/org/joda/joda-beans-maven-plugin
# install
install:
  - mvn --version
script:
  - mvn install site -e -B
